from __future__ import annotations

NOTE_RECOMMENDATION_LEVEL_STRONGLY_RECOMMENDED = "strongly_recommended"
NOTE_RECOMMENDATION_LEVEL_RECOMMENDED = "recommended"
NOTE_RECOMMENDATION_LEVEL_NEUTRAL = "neutral"
NOTE_RECOMMENDATION_LEVEL_NOT_RECOMMENDED = "not_recommended"

NOTE_RECOMMENDATION_LEVEL_VALUES = {
    NOTE_RECOMMENDATION_LEVEL_STRONGLY_RECOMMENDED,
    NOTE_RECOMMENDATION_LEVEL_RECOMMENDED,
    NOTE_RECOMMENDATION_LEVEL_NEUTRAL,
    NOTE_RECOMMENDATION_LEVEL_NOT_RECOMMENDED,
}
DEFAULT_NOTE_RECOMMENDATION_LEVEL = NOTE_RECOMMENDATION_LEVEL_NEUTRAL


def normalize_note_recommendation_level(value: str | None) -> str:
    if value in NOTE_RECOMMENDATION_LEVEL_VALUES:
        return value
    return DEFAULT_NOTE_RECOMMENDATION_LEVEL
